### ISSUE TITLE
Best outgroup(s) for species tree error

### ISSUE THREAD

**Issue by yuntwang** [davidemms/OrthoFinder#273]
Hi,When I use OrthoFinder deal with example data and encounter error,
my command line:
./OrthoFinder-2.3.3/orthofinder/orthofinder.py  -t 10 -a 10 -M msa -S diamond -A muscle -T fasttree -f data/
Error:
Inferring remaining multiple sequence alignments and gene trees
---------------------------------------------------------------
2019-07-02 15:52:32 : Done 0 of 260
2019-07-02 15:52:36 : Done 100 of 260
2019-07-02 15:52:37 : Done 200 of 260
2019-07-02 15:52:47 : Done MSA/Trees

Best outgroup(s) for species tree
---------------------------------
2019-07-02 15:52:47 : Starting STRIDE
Traceback (most recent call last):
  File "/share/nas1/wangyt/software/OrthoFinder-2.3.3/orthofinder/orthofinder.py", line 1652, in <module>
    GetOrthologues(speciesInfoObj, options, program_caller, orthogroupsResultsFilesString)
  File "/share/nas1/wangyt/software/OrthoFinder-2.3.3/orthofinder/orthofinder.py", line 1482, in GetOrthologues
    options.name)
  File "/share/nas1/wangyt/software/OrthoFinder-2.3.3/orthofinder/scripts/orthologues.py", line 979, in OrthologuesWorkflow
    roots, clusters_counter, rootedSpeciesTreeFN, nSupport, _, _, all_stride_dup_genes = stride.GetRoot(spTreeFN_ids, files.FileHandler.GetOGsTreeDir(), stride.GeneToSpecies_dash, nHighParallel, qWriteRootedTree=True)
  File "/share/nas1/wangyt/software/OrthoFinder-2.3.3/orthofinder/scripts/stride.py", line 507, in GetRoot
    pool = mp.Pool(nProcessors, maxtasksperchild=1)       
TypeError: Pool() got an unexpected keyword argument 'maxtasksperchild'

**Comment by davidemms** [comment]
Hi

What version of python are you using? It should work fine with version 2.7.

All the best
David

**Comment by yuntwang** [comment]
Hi，@davidemms
**which python
/share/nas2/genome/biosoft/Python/2.7.8/bin/python**

**Comment by davidemms** [comment]
Hi

The documentation says that version 2.7.8 supports 'maxtasksperchild': https://docs.python.org/release/2.7.8/library/multiprocessing.html#module-multiprocessing.pool

Nevertheless, I would recommend using the binary version of OrthoFinder: https://github.com/davidemms/OrthoFinder/releases/download/2.3.3/OrthoFinder-2.3.3.tar.gz or alternatively, updating to python 2.7.16.

All the best
David
